[package]
name = "rapl_interface"
version = "0.1.0"
edition = "2021"

[lib]
name = "rapl_interface"
crate-type = ["cdylib"]

[build-dependencies]
sysinfo = "0.33.1"

[dependencies]
csv = "1.3"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
jni = "0.21"
